server:
  port: 9090

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/projectmgmt/**

        -  id: task-service
           uri: lb://task-service
           predicates:
            - Path=/taskservice/**
           filters:
             - RewritePath=/taskservice,/taskservice




eureka:
  instance:
    prefer-ip-address : true
  client:
    fetch-registry : true
    register-with-eureka : true
    service-url :
     defaultZone : http://34.229.148.24:8761/eureka/


