package com.cts.iiht.taskservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.*;
import java.time.format.DateTimeFormatter;


@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "tasks")
public class Task {

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String taskName;

    @DynamoDBAttribute
    private String deliverables;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate taskStartDate;

    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateConverter.class)
    private LocalDate taskEndDate;

    @DynamoDBAttribute
    private String memberId;

    public static class InetgerConverter implements DynamoDBTypeConverter<String, Integer> {

        @Override
        public String convert(Integer object) {
            return String.valueOf(object);
        }

        @Override
        public Integer unconvert(String object) {
            return Integer.parseInt(object);
        }
    }

    public static class LocalDateConverter implements DynamoDBTypeConverter<String, LocalDate> {

        @Override
        public String convert(LocalDate object) {
            return object.toString();
        }

        @Override
        public LocalDate unconvert(String object) {
            // Define the desired date format
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

            // Parse the string to LocalDate using the formatter
            LocalDate localDate = LocalDate.parse(object, formatter);
            return localDate;
        }
    }
}
